### ISSUE TITLE
Casting Error

### ISSUE THREAD

**Issue by ghost** [campudus/vertx-session-manager#5]
I'm getting the following error when running the module under the gradle template at https://github.com/vert-x/vertx-gradle-template

SEVERE: Exception in Java verticle
java.lang.ClassCastException: com.campudus.vertx.sessionmanager.SessionManager cannot be cast to org.vertx.scala.platform.Verticle

**Comment by Narigo** [comment]
How are you running it exactly? What steps would I need to take to reproduce this error?

The session manager doesn't use the official Scala API (yet) as it was written before that came out. We extend/use the Java classes directly, so I don't really get why Vert.x is trying to cast this into a Scala Verticle...

**Comment by ghost** [comment]
Sorry I missed a step and perhaps I'm doing something wrong. I cloned https://github.com/vert-x/vertx-gradle-template and https://github.com/campudus/vertx-gradle-scala-template. I then added the following conf.json file to each of the folders so I can run 2 tests:

{
    "address": "test.session-manager",
    "timeout": 900000,
    "cleaner": "test.session-cleanup",
    "prefix": "session-client."
}

For each of them I've run:

./gradlew build

vertx runmod com.campudus~session-manager~2.0.1-final -conf conf.json

I then got the error
Failed in deploying module 
java.lang.NoClassDefFoundError: scala/Option

I then tried editing mods/com.campudus~session-manager~2.0.1-final/mod.json and adding prepending the main with scala so it read "scala:com.campudus.vertx.sessionmanager.SessionManager"

Then I got the error
com.campudus.vertx.sessionmanager.SessionManager cannot be cast to org.vertx.scala.platform.Verticle

**Comment by Narigo** [comment]
Okay, so the first thing is: You won't need vertx-gradle-scala-template. That's outdated and is not needed anymore if you want to develop in Scala. Since Vert.x 2.1+, there is Scala support out of the box through the lang-scala module.

If you just need this module to work and don't use Scala yourself, you need to add the Scala library to your classpath. If you use Gradle, you can add it by copy & pasting the scala-library dependency in the module to the module you develop (https://github.com/campudus/vertx-session-manager/blob/master/build.gradle#L8). Any 2.10.x version of Scala should be okay, we used 2.10.2 here for all the tests, but we're using the session manager + Scala 2.10.4 in another project without problems right now.

So this should work with Gradle:

```
dependencies {
  provided "org.scala-lang:scala-library:2.10.4"
}
```

For usage with Vert.x directly, download the Scala library jar and add it to your classpath. Maybe this works:

`vertx runmod com.campudus~session-manager~2.0.1-final -conf conf.json -cp scala-library.jar`

I usually have a small "starter" app that deploys all the modules I need through `container.deployModule(...)`.

**Comment by ghost** [comment]
Thank you very much. I can confirm that if I add 

dependencies {
  compile "org.scala-lang:scala-library:2.10.4"
}

to the build.json of the latest gradle template it works. I'm running it from a module with the following code:

JsonObject sessionConf = appConfig.getObject("sessionConf");
container.deployModule("com.campudus~session-manager~2.0.1-final", sessionConf);

**Comment by Narigo** [comment]
Okay, cool!
